In [1]:
import pandas as pd

## Блок 1. Знакомство со структурой данных

In [2]:
calendar = pd.read_parquet("../data/calendar.parquet")
dataframe = pd.read_parquet("../data/dataframe.parquet")
iavd = pd.read_parquet("../data/iavd_incidents_raw_target.parquet")
iavd1000 = pd.read_parquet("../data/iavd_1000_incidents_raw_target.parquet")

In [3]:
calendar.head()

,Дата,Номер недели,Год,Месяц,МесяцГод,День,ДеньМесяц,ДеньМесяц_Недели,Дата_ДеньНедели,Квартал,...,Неделя Год,День недели,_180 дней,_90 дней,_30 дней,_7 дней,Тип дня,Год ГИС,Номер недели ГИС,НеделяГод ГИС
0,2024-04-12,15,2024,4,2024-04-01,12,2024-04-12,2024-04-12,2024-04-12,2,...,2024-04-15,4,NaN,NaN,NaN,NaN,2,2024,15,2024-04-08
1,2024-05-07,19,2024,5,2024-05-01,7,2024-05-07,2024-05-07,2024-05-07,2,...,2024-05-13,1,NaN,NaN,NaN,NaN,1,2024,19,2024-05-06
2,2024-05-25,21,2024,5,2024-05-01,25,2024-05-25,2024-05-25,2024-05-25,2,...,2024-05-27,5,NaN,NaN,NaN,NaN,4,2024,21,2024-05-20
3,2024-06-28,26,2024,6,2024-06-01,28,2024-06-28,2024-06-28,2024-06-28,2,...,2024-07-01,4,NaN,NaN,NaN,NaN,2,2024,26,2024-06-24
4,2024-06-01,22,2024,6,2024-06-01,1,2024-06-01,2024-06-01,2024-06-01,2,...,2024-06-03,5,NaN,NaN,NaN,NaN,4,2024,22,2024-05-27

In [4]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Дата              510 non-null    object
 1   Номер недели      510 non-null    int64
 2   Год               510 non-null    int64
 3   Месяц             510 non-null    int64
 4   МесяцГод          510 non-null    object
 5   День              510 non-null    int64
 6   ДеньМесяц         510 non-null    object
 7   ДеньМесяц_Недели  510 non-null    object
 8   Дата_ДеньНедели   510 non-null    object
 9   Квартал           510 non-null    int64
 10  НеделяГод         510 non-null    object
 11  Неделя Год        510 non-null    object
 12  День недели       510 non-null    int64
 13  _180 дней         178 non-null    float64
 14  _90 дней          88 non-null     float64
 15  _30 дней          28 non-null     float64
 16  _7 дней           5 non-null      float64
 17  Тип дня           510 non-null    int64
 18  Год ГИС           510 non-null    int64
 19  Номер недели ГИС  510 non-null    int64
 20  НеделяГод ГИС     510 non-null    object
dtypes: float64(4), int64(9), object(8)
memory usage: 83.8+ KB

In [5]:
dataframe.head()

         Дата  Период
0  2025-08-30  7 дней
1  2025-08-31  7 дней
2  2025-09-01  7 дней
3  2025-09-02  7 дней
4  2025-09-03  7 дней

In [6]:
iavd.head()

,EntityId,Создан,Дата,Вердикт,Дата закрытия (факт),Попытка эксплуатации,Тип инцидента,Список вредоносных команд,Критичность,Ответственный,...,Открыт для редактирования,Белый список,Ложное срабатывание,Инцидент был изменен,Время решения,SLA по устранению Атаки,SLA по взятию в работу Атаки,Период взятия в работу,задержка перед автоназначением,verdict
0,7291,2024-04-12 17:06:04.854999+00:00,2024-04-12,Закрыт из родительской атаки,NaT,None,Общий Инцидент ИБ,None,Низкая,Цветкова Дарья Дмитриевна,...,None,None,None,False,2.245495e+09,28800000.0,21600000.0,5.883327e+08,NaN,6
1,182208,2024-05-07 11:37:59.010000+00:00,2024-05-07,Не указан,NaT,Exploitation of Remote Services,Вирус не вылечен~~||~~Подозрительный трафик,None,Средняя,Цветкова Дарья Дмитриевна,...,False,None,None,False,0.000000e+00,28800000.0,21600000.0,0.000000e+00,NaN,0
2,185122,2024-05-25 02:22:57.095000+00:00,2024-05-25,False Positive,NaT,Exploitation of Remote Services,Успешный вход под несколькими УЗ на один хост,None,Средняя,,...,False,None,True,False,0.000000e+00,86400000.0,28800000.0,0.000000e+00,NaN,1
3,291395,2024-06-28 20:27:48.884999+00:00,2024-06-28,Не указан,2024-06-28 20:52:29.748999+00:00,None,Выполнение подозрительной команды,None,Низкая,Соколов Александр Михайлович,...,False,None,None,False,2.701098e+03,3600000.0,600000.0,1.481010e+06,1.719608e+09,0
4,185129,2024-05-25 06:47:52.387000+00:00,2024-05-25,False Positive,NaT,None,Выполнение подозрительной команды,None,Средняя,,...,False,None,True,False,0.000000e+00,28800000.0,21600000.0,0.000000e+00,NaN,1

In [7]:
len(iavd)

240295

In [8]:
iavd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240295 entries, 0 to 240294
Data columns (total 97 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   EntityId                                         240295 non-null  int64
 1   Создан                                           240295 non-null  datetime64[us, UTC]
 2   Дата                                             240295 non-null  object
 3   Вердикт                                          240295 non-null  object
 4   Дата закрытия (факт)                             198156 non-null  datetime64[us, UTC]
 5   Попытка эксплуатации                             26415 non-null   object
 6   Тип инцидента                                    240179 non-null  object
 7   Список вредоносных команд                        3858 non-null    object
 8   Критичность                                      240295 non-null  object
 9   Ответственный                                    239296 non-null  object
 10  Пиктограмма IRP                                  240290 non-null  object
 11  Прошлый ответственный                            1095 non-null    object
 12  Типы угроз                                       653 non-null     object
 13  Группа устранения                                240258 non-null  object
 14  Рекомендации по плейбуку                         72188 non-null   object
 15  Фаза реагирования                                240295 non-null  object
 16  Теги                                             37724 non-null   object
 17  Источник инцидента                               240290 non-null  object
 18  Вендор из сием                                   60326 non-null   object
 19  Организация                                      240295 non-null  object
 20  Наименование                                     240249 non-null  object
 21  suser                                            66495 non-null   object
 22  filePath                                         5924 non-null    object
 23  processParentPath                                41506 non-null   object
 24  objectLinks                                      51318 non-null   object
 25  Ответсвенный по РП                               238953 non-null  float64
 26  Принятые меры                                    228346 non-null  object
 27  objectValue                                      44187 non-null   object
 28  Значение Атаки (группировка)                     232093 non-null  object
 29  Решение                                          206475 non-null  object
 30  Алерт                                            179635 non-null  object
 31  Правило корреляции SIEM                          227055 non-null  object
 32  Критичность инцидента в источнике                240147 non-null  object
 33  Полное имя                                       19291 non-null   object
 34  Статус инцидента из SIEM                         240129 non-null  object
 35  Значение Инцидента (группировка)                 231276 non-null  object
 36  Значение Инцидента (группировка по типу)         212275 non-null  object
 37  Файловый ресурс                                  59257 non-null   object
 38  Имя файла-IRP                                    59257 non-null   object
 39  Принятые меры из SIEM                            169892 non-null  object
 40  Команда                                          175377 non-null  object
 41  CMDLINE                                          70465 non-null   object
 42  Конвейер SIEM                                    172630 non-null  object
 43  Описание инцидента                               240235 non-null  object
 44  Hostname Цели                                    133743 non-null  object
 45  categoryHigh                                     120073 non-null  object
 46  categoryLow                                      133975 non-null  object
 47  categoryMain                                     132826 non-null  object
 48  commandName                                      21864 non-null   object
 49  duser                                            56063 non-null   object
 50  object                                           121240 non-null  object
 51  object.name                                      57915 non-null   object
 52  Привилегии аккаунта                              12181 non-null   object
 53  processName                                      44557 non-null   object
 54  processParentName                                42388 non-null   object
 55  processPath                                      52226 non-null   object
 56  Hostname атакующего                              124760 non-null  object
 57  Инцидент в Источнике                             240129 non-null  object
 58  Комментарий                                      171139 non-null  object
 59  Ошибки                                           13 non-null      object
 60  Ссылка в NAD (actual)                            29499 non-null   object
 61  Количество инцидентов                            40492 non-null   float64
 62  dst                                              95271 non-null   object
 63  src                                              80807 non-null   object
 64  Дата закрытия                                    162318 non-null  datetime64[us, UTC]
 65  Время первого события                            198477 non-null  datetime64[us, UTC]
 66  Время последнего события                         198475 non-null  datetime64[us, UTC]
 67  Дата создания в источнике                        240129 non-null  datetime64[us, UTC]
 68  Дата изменения в источнике                       240129 non-null  datetime64[us, UTC]
 69  Дата взятия в работу                             191924 non-null  datetime64[us, UTC]
 70  Время Решения                                    195951 non-null  datetime64[us, UTC]
 71  Начало паузы                                     126959 non-null  datetime64[us, UTC]
 72  Конец паузы                                      126959 non-null  datetime64[us, UTC]
 73  Связывались с пользователем/эскалировали в ГИБ?  52831 non-null   object
 74  Спам                                             133263 non-null  object
 75  Эскалировался на L2?                             1756 non-null    object
 76  Пауза                                            126958 non-null  object
 77  На мониторинг                                    92522 non-null   object
 78  Заблокировать                                    92522 non-null   object
 79  SLA просрочен (взятие в работу)                  184219 non-null  object
 80  Проверка на FP выполнена                         162714 non-null  object
 81  Выполнено первичное сдерживание                  112450 non-null  object
 82  Обогащение выполнено                             162469 non-null  object
 83  Классификация выполнена                          199243 non-null  object
 84  Успех brute force                                1410 non-null    object
 85  False Positive                                   9656 non-null    object
 86  Легитимность действия                            240250 non-null  object
 87  Открыт для редактирования                        140141 non-null  object
 88  Белый список                                     32882 non-null   object
 89  Ложное срабатывание                              175047 non-null  object
 90  Инцидент был изменен                             240175 non-null  object
 91  Время решения                                    238623 non-null  float64
 92  SLA по устранению Атаки                          240265 non-null  float64
 93  SLA по взятию в работу Атаки                     240265 non-null  float64
 94  Период взятия в работу                           239731 non-null  float64
 95  задержка перед автоназначением                   199684 non-null  float64
 96  verdict                                          240295 non-null  int64
dtypes: datetime64[us, UTC](11), float64(7), int64(2), object(77)
memory usage: 177.8+ MB

In [9]:
len(iavd1000)

1000

In [10]:
iavd1000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 97 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   EntityId                                         1000 non-null   int64
 1   Создан                                           1000 non-null   datetime64[us, UTC]
 2   Дата                                             1000 non-null   object
 3   Вердикт                                          1000 non-null   object
 4   Дата закрытия (факт)                             89 non-null     datetime64[us, UTC]
 5   Попытка эксплуатации                             197 non-null    object
 6   Тип инцидента                                    1000 non-null   object
 7   Список вредоносных команд                        2 non-null      object
 8   Критичность                                      1000 non-null   object
 9   Ответственный                                    820 non-null    object
 10  Пиктограмма IRP                                  1000 non-null   object
 11  Прошлый ответственный                            0 non-null      object
 12  Типы угроз                                       4 non-null      object
 13  Группа устранения                                1000 non-null   object
 14  Рекомендации по плейбуку                         4 non-null      object
 15  Фаза реагирования                                1000 non-null   object
 16  Теги                                             199 non-null    object
 17  Источник инцидента                               1000 non-null   object
 18  Вендор из сием                                   2 non-null      object
 19  Организация                                      1000 non-null   object
 20  Наименование                                     1000 non-null   object
 21  suser                                            113 non-null    object
 22  filePath                                         1 non-null      object
 23  processParentPath                                91 non-null     object
 24  objectLinks                                      104 non-null    object
 25  Ответсвенный по РП                               995 non-null    float64
 26  Принятые меры                                    816 non-null    object
 27  objectValue                                      89 non-null     object
 28  Значение Атаки (группировка)                     987 non-null    object
 29  Решение                                          505 non-null    object
 30  Алерт                                            981 non-null    object
 31  Правило корреляции SIEM                          982 non-null    object
 32  Критичность инцидента в источнике                1000 non-null   object
 33  Полное имя                                       8 non-null      object
 34  Статус инцидента из SIEM                         999 non-null    object
 35  Значение Инцидента (группировка)                 986 non-null    object
 36  Значение Инцидента (группировка по типу)         982 non-null    object
 37  Файловый ресурс                                  262 non-null    object
 38  Имя файла-IRP                                    262 non-null    object
 39  Принятые меры из SIEM                            82 non-null     object
 40  Команда                                          462 non-null    object
 41  CMDLINE                                          19 non-null     object
 42  Конвейер SIEM                                    29 non-null     object
 43  Описание инцидента                               1000 non-null   object
 44  Hostname Цели                                    167 non-null    object
 45  categoryHigh                                     172 non-null    object
 46  categoryLow                                      174 non-null    object
 47  categoryMain                                     174 non-null    object
 48  commandName                                      2 non-null      object
 49  duser                                            117 non-null    object
 50  object                                           174 non-null    object
 51  object.name                                      8 non-null      object
 52  Привилегии аккаунта                              1 non-null      object
 53  processName                                      93 non-null     object
 54  processParentName                                91 non-null     object
 55  processPath                                      94 non-null     object
 56  Hostname атакующего                              164 non-null    object
 57  Инцидент в Источнике                             999 non-null    object
 58  Комментарий                                      499 non-null    object
 59  Ошибки                                           0 non-null      object
 60  Ссылка в NAD (actual)                            1 non-null      object
 61  Количество инцидентов                            837 non-null    float64
 62  dst                                              179 non-null    object
 63  src                                              202 non-null    object
 64  Дата закрытия                                    99 non-null     datetime64[us, UTC]
 65  Время первого события                            996 non-null    datetime64[us, UTC]
 66  Время последнего события                         996 non-null    datetime64[us, UTC]
 67  Дата создания в источнике                        999 non-null    datetime64[us, UTC]
 68  Дата изменения в источнике                       999 non-null    datetime64[us, UTC]
 69  Дата взятия в работу                             754 non-null    datetime64[us, UTC]
 70  Время Решения                                    89 non-null     datetime64[us, UTC]
 71  Начало паузы                                     4 non-null      datetime64[us, UTC]
 72  Конец паузы                                      4 non-null      datetime64[us, UTC]
 73  Связывались с пользователем/эскалировали в ГИБ?  6 non-null      object
 74  Спам                                             8 non-null      object
 75  Эскалировался на L2?                             0 non-null      object
 76  Пауза                                            4 non-null      object
 77  На мониторинг                                    50 non-null     object
 78  Заблокировать                                    50 non-null     object
 79  SLA просрочен (взятие в работу)                  574 non-null    object
 80  Проверка на FP выполнена                         969 non-null    object
 81  Выполнено первичное сдерживание                  930 non-null    object
 82  Обогащение выполнено                             969 non-null    object
 83  Классификация выполнена                          1000 non-null   object
 84  Успех brute force                                49 non-null     object
 85  False Positive                                   522 non-null    object
 86  Легитимность действия                            999 non-null    object
 87  Открыт для редактирования                        676 non-null    object
 88  Белый список                                     112 non-null    object
 89  Ложное срабатывание                              255 non-null    object
 90  Инцидент был изменен                             999 non-null    object
 91  Время решения                                    996 non-null    float64
 92  SLA по устранению Атаки                          1000 non-null   int64
 93  SLA по взятию в работу Атаки                     1000 non-null   int64
 94  Период взятия в работу                           997 non-null    float64
 95  задержка перед автоназначением                   89 non-null     float64
 96  verdict                                          1000 non-null   int64
dtypes: datetime64[us, UTC](11), float64(5), int64(4), object(77)
memory usage: 757.9+ KB

In [11]:
df = iavd

### 1.1 Сколько строк и столбцов в датасете?

In [12]:
df.shape

(240295, 97)

### 1.2 Сколько полей строкового, числового и datetime-типа?

In [13]:
df.dtypes.value_counts()

object                 77
datetime64[us, UTC]    11
float64                 7
int64                   2
Name: count, dtype: int64

### 1.3 Какие 3 поля заполнены хуже всего?

In [17]:
df.isna().mean().nlargest(3)

Ошибки                   0.999946
Типы угроз               0.997283
Прошлый ответственный    0.995443
dtype: float64

### 1.4 Сколько полей заполнены полностью (без NaN)?

In [18]:
(df.isna().mean()==0).sum()

np.int64(8)

In [25]:
df.columns[df.isna().mean()==0]

Index(['EntityId', 'Создан', 'Дата', 'Вердикт', 'Критичность',
       'Фаза реагирования', 'Организация', 'verdict'],
      dtype='object')

### 1.5 Сколько уникальных значений у Вердикт?

In [30]:
df['Вердикт'].nunique()

7

### 1.6 Сколько уникальных значений у Критичность?

In [31]:
df['Критичность'].nunique()

5

### 1.7 Сколько карточек содержат список пар в Значение Инцидента (группировка)?

Всего:

In [43]:
df['Значение Инцидента (группировка)'].str.contains(r'\|', na=False).mean()

np.float64(0.96222975925425)

непустых:

In [42]:
col = df['Значение Инцидента (группировка)']
has_value = col.notna()
has_pairs = col.str.contains(r'\|', na=False)

(has_pairs & has_value).sum() / has_value.sum()

np.float64(0.9997535412234733)

### 1.8 Максимальное число элементов списка Значение Инцидента у одной карточки?

In [45]:
df['Значение Инцидента (группировка)'].str.split('~~||~~').str.len().max()

np.float64(55353.0)

### 1.9 Есть ли дубликаты EntityId?

In [47]:
df['EntityId'].duplicated().sum()

np.int64(0)

### 1.10 Сколько строк даст разворот Значение Инцидента по элементам?

In [49]:
len(df['Значение Инцидента (группировка)'].str.split('~~||~~').explode())

34687107

### 1.11 Какое поле — полный аналог Вердикт в числовом виде?

In [50]:
df['Вердикт']

0         Закрыт из родительской атаки
1                            Не указан
2                       False Positive
3                            Не указан
4                       False Positive
                      ...
240290                       Не указан
240291                       Не указан
240292                       Не указан
240293                       Не указан
240294                       Не указан
Name: Вердикт, Length: 240295, dtype: object

In [51]:
df['verdict']

0         6
1         0
2         1
3         0
4         1
         ..
240290    0
240291    0
240292    0
240293    0
240294    0
Name: verdict, Length: 240295, dtype: int64